/**
 * WASM Bridge for CyberEdu Zero-Trust Academy
 * 
 * This module provides TypeScript bindings to the Rust WASM core.
 * It handles loading the WASM module and exposing functions to React components.
 */

import type { CommandResponse } from './types';

// WASM module instance (lazy loaded)
let wasmModule: CoreWasmModule | null = null;
let wasmLoading: Promise<CoreWasmModule> | null = null;

// Type definitions for the WASM module interface
interface CoreWasmModule {
  init(): void;
  process_command(command: string, args: string): string;
  get_version(): string;
  health_check(): boolean;
  init_procedural_lab(seed: number): void;
  get_challenge_status(): string;
  
  // Network functions
  scan_host(args: string): string;
  ping_host(args: string): string;
  http_get(args: string): string;
  
  // Crypto functions
  hash_data(args: string): string;
  encrypt_data(args: string): string;
  decrypt_data(args: string): string;
  generate_key(args: string): string;
  
  // Log analyzer functions
  analyze(args: string): string;
  search(args: string): string;
  
  // Filesystem functions
  list_directory(args: string): string;
  read_file(args: string): string;
  create_directory(args: string): string;
  create_file(args: string): string;
  
  // Flag validator functions
  submit_flag(args: string): string;
  check_flag(args: string): string;
  
  // Rate limiter functions
  check_rate(args: string): string;
  reset_rate(args: string): string;
}

/**
 * Load and initialize the WASM module
 */
export async function loadWasmModule(): Promise<CoreWasmModule> {
  if (wasmModule) {
    return wasmModule;
  }

  if (wasmLoading) {
    return wasmLoading;
  }

  wasmLoading = (async () => {
    try {
      // Dynamic import of the WASM module generated by wasm-bindgen
      const wasm = await import('@cyber-edu/core-wasm');
      
      // Initialize the WASM module
      await wasm.default();
      
      // Seed the procedural lab challenge with current timestamp
      const seed = Date.now() % 4294967295; // Ensure it fits in u32
      wasm.init_procedural_lab(seed);
      console.log('[WASM] Procedural lab seeded with:', seed);
      
      wasmModule = wasm;
      console.log('[WASM] Module loaded successfully, version:', wasm.get_version());
      
      return wasm;
    } catch (error) {
      console.error('[WASM] Failed to load module:', error);
      throw new Error(`Failed to load WASM module: ${error}`);
    }
  })();

  return wasmLoading;
}

/**
 * Parse a JSON response from WASM into a CommandResponse
 */
function parseResponse(jsonString: string): CommandResponse {
  try {
    return JSON.parse(jsonString) as CommandResponse;
  } catch (error) {
    return {
      success: false,
      output: '',
      error: `Failed to parse WASM response: ${error}`,
    };
  }
}

/**
 * Process a command through the WASM module
 * This is the main entry point for command execution
 */
export async function processCommand(
  command: string,
  args: string = ''
): Promise<CommandResponse> {
  try {
    const wasm = await loadWasmModule();
    const jsonString = wasm.process_command(command, args);
    return parseResponse(jsonString);
  } catch (error) {
    return {
      success: false,
      output: '',
      error: `WASM execution error: ${error}`,
    };
  }
}

/**
 * Get the WASM module version
 */
export async function getVersion(): Promise<string> {
  const wasm = await loadWasmModule();
  return wasm.get_version();
}

/**
 * Health check for the WASM module
 */
export async function healthCheck(): Promise<boolean> {
  try {
    const wasm = await loadWasmModule();
    return wasm.health_check();
  } catch {
    return false;
  }
}

// ============================================================================
// Network Functions
// ============================================================================

/**
 * Scan a host (simulated nmap)
 */
export async function scanHost(host: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.scan_host(host));
}

/**
 * Ping a host (simulated)
 */
export async function pingHost(host: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.ping_host(host));
}

/**
 * HTTP GET request (simulated)
 */
export async function httpGet(url: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.http_get(url));
}

// ============================================================================
// Crypto Functions
// ============================================================================

/**
 * Hash data using specified algorithm (sha256 or sha512)
 * Format: "algorithm:data" e.g., "sha256:hello"
 */
export async function hashData(algorithm: string, data: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.hash_data(`${algorithm}:${data}`));
}

/**
 * Encrypt data using AES-256-GCM
 * Format: "key:data"
 */
export async function encryptData(key: string, data: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.encrypt_data(`${key}:${data}`));
}

/**
 * Decrypt data using AES-256-GCM
 * Format: "key:encrypted_data"
 */
export async function decryptData(key: string, encryptedData: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.decrypt_data(`${key}:${encryptedData}`));
}

/**
 * Generate a random key of specified size (in bytes)
 */
export async function generateKey(size: number = 32): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.generate_key(size.toString()));
}

// ============================================================================
// Log Analyzer Functions
// ============================================================================

/**
 * Analyze log content for patterns, levels, IPs, timestamps
 */
export async function analyzeLog(logContent: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.analyze(logContent));
}

/**
 * Search log content with regex pattern
 * Format: "pattern:log_content"
 */
export async function searchLog(pattern: string, logContent: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.search(`${pattern}:${logContent}`));
}

// ============================================================================
// Filesystem Functions
// ============================================================================

/**
 * List directory contents
 */
export async function listDirectory(path: string = ''): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.list_directory(path));
}

/**
 * Read file contents
 */
export async function readFile(path: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.read_file(path));
}

/**
 * Create a new directory
 */
export async function createDirectory(path: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.create_directory(path));
}

/**
 * Create a new file (touch)
 */
export async function createFile(path: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.create_file(path));
}

// ============================================================================
// Flag Validator Functions
// ============================================================================

/**
 * Submit a CTF flag for validation
 */
export async function submitFlag(flag: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.submit_flag(flag));
}

/**
 * Check if a flag exists in the system
 */
export async function checkFlag(flag: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.check_flag(flag));
}

// ============================================================================
// Rate Limiter Functions
// ============================================================================

/**
 * Check rate limit for an operation
 * Format: "operation:client_id"
 */
export async function checkRateLimit(operation: string, clientId: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.check_rate(`${operation}:${clientId}`));
}

/**
 * Reset rate limit for an operation
 * Format: "operation:client_id"
 */
export async function resetRateLimit(operation: string, clientId: string): Promise<CommandResponse> {
  const wasm = await loadWasmModule();
  return parseResponse(wasm.reset_rate(`${operation}:${clientId}`));
}

/**
 * Initialize all WASM modules on app startup
 */
export async function initializeWasm(): Promise<void> {
  try {
    await loadWasmModule();
    console.log('[WASM] Initialization complete');
  } catch (error) {
    console.error('[WASM] Initialization failed:', error);
    throw error;
  }
}

export default {
  loadWasmModule,
  processCommand,
  getVersion,
  healthCheck,
  scanHost,
  pingHost,
  httpGet,
  hashData,
  encryptData,
  decryptData,
  generateKey,
  analyzeLog,
  searchLog,
  listDirectory,
  readFile,
  createDirectory,
  createFile,
  submitFlag,
  checkFlag,
  checkRateLimit,
  resetRateLimit,
  initializeWasm,
};
